import { test, expect } from '@playwright/test';
test('Регистрация → автомобиль → связанное ТО → отчёт без аккаунта',async({page,browser})=>{
 await page.goto('/register');
 await page.getByLabel('Ваше имя',{exact:true}).fill('Проверка E2E');
 await page.getByLabel('Email',{exact:true}).fill(`e2e-${Date.now()}@carhistory.test`);
 await page.getByLabel('Пароль',{exact:true}).fill('E2ePassword2026!');
 await page.getByLabel('Повторите пароль',{exact:true}).fill('E2ePassword2026!');
 await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Ваш гараж.',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Добавить автомобиль',exact:true}).last().click();
 await page.getByLabel('Марка',{exact:true}).fill('E2E');
 await page.getByLabel('Модель',{exact:true}).fill('Transaction');
 await page.getByRole('button',{name:'Продолжить',exact:true}).click();
 await expect(page.getByText('Шаг 2 из 2 · Пробег и дополнительные данные')).toBeVisible();
 await expect(page).toHaveURL(/dashboard/);
 await page.getByLabel('Одометр, км',{exact:true}).fill('1000');
 await page.getByRole('button',{name:'Добавить автомобиль',exact:true}).click();
 await expect(page.getByRole('heading',{name:'E2E Transaction',exact:true})).toBeVisible();
 const carUrl=page.url();
 await page.getByRole('button',{name:'Добавить запись',exact:true}).last().click();
 await page.getByLabel('Название',{exact:true}).fill('Тестовое ТО');
 await page.getByLabel('Одометр, км',{exact:true}).fill('1100');
 await page.getByLabel('Стоимость работы',{exact:true}).fill('1500');
 await page.getByRole('button',{name:'Добавить',exact:true}).click();
 await page.getByLabel('Название детали',{exact:true}).fill('Масло');
 await page.getByLabel('Количество',{exact:true}).fill('6');
 await page.getByLabel('Цена за единицу',{exact:true}).fill('1400');
 await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();
 await expect(page.getByRole('button').filter({hasText:'Тестовое ТО'})).toHaveCount(1);
 await page.goto(`${carUrl}/expenses`);
 await expect(page.getByRole('link').filter({hasText:'Тестовое ТО'})).toHaveCount(1);
 await expect(page.getByText('9 900 сом',{exact:true}).first()).toBeVisible();
 await page.goto(`${carUrl}/public-report`);
 await page.getByRole('button',{name:'Создать отчёт',exact:true}).click();
 await page.getByRole('button',{name:'Предпросмотр',exact:true}).click();
 await expect(page.getByText('Предпросмотр снимка',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Опубликовать',exact:true}).click();
 const href=await page.getByRole('link',{name:'Открыть',exact:true}).getAttribute('href');
 const context=await browser.newContext();const buyer=await context.newPage();await buyer.goto(new URL(href!,carUrl).href);
 await expect(buyer.getByRole('heading',{name:'E2E Transaction',exact:true})).toBeVisible();
 await expect(buyer.getByText('Тестовое ТО',{exact:true})).toBeVisible();
 await expect(buyer.getByText('Данные о ДТП не включены в отчёт',{exact:true})).toBeVisible();
 await context.close();
});
for(const width of [360,390,768,1024,1440])test(`Гараж не переполняет экран ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('owner@carhistory.test');await page.getByLabel('Пароль',{exact:true}).fill('CarHistory2026!');await page.getByRole('button',{name:'Войти',exact:true}).click();await expect(page.getByRole('heading',{name:'Ваш гараж.',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
